# Generated by Django 5.1.2 on 2024-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='is_include',
        ),
        migrations.AddField(
            model_name='planfeature',
            name='is_include',
            field=models.BooleanField(blank='false', null='false'),
            preserve_default='false',
        ),
    ]
