# Generated by Django 5.1.2 on 2024-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plans_is_include_planfeature_is_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_price',
            field=models.CharField(blank='false', max_length=20, null='false'),
            preserve_default='false',
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(blank='false', max_length=50, null='false'),
        ),
    ]
