# Generated by Django 5.1.2 on 2024-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_level',
            field=models.CharField(choices=[('enem', 'Enem e Vestibular'), ('superior', 'Ensino Superior'), ('concurso', 'Concurso')], default='enem', max_length=10),
        ),
    ]
